# docker-compose.yml
version: '3.8'

services:
  flask_ltk_report:
    build: .
    container_name: flask_ltk_report
    environment:
      - ENV=prod
    restart: always
    ports:
      - "2512:2512"
    command: ["python3","src/app.py"]